CREATE DATABASE roguelitee;
USE roguelitee;
CREATE TABLE Eventos (id SMALLINT PRIMARY KEY, cadenaTextoEvento VARCHAR(400) NOT NULL, idEventos VARCHAR(40) NOT NULL, idObjetos VARCHAR(40), cantidadCordura SMALLINT, cantidadCarisma SMALLINT, cantidadIntimidacion SMALLINT, cantidadInteligencia SMALLINT, cantidadSuerte SMALLINT);
INSERT INTO Eventos VALUES (1, 'Cortar la telaraña con el cuchillo.', 'ARANA_REDES', 'ITEM_CUCHILLO', 0, 0, 0, 0, 0);
INSERT INTO Eventos VALUES (2, 'Pasar desapercibido con el traje impecable.', 'ARMADURA_ABANDONADA', 'ITEM_TRAJE_IMPECABLE', 0, 0, 0, 0, 0);
INSERT INTO Eventos VALUES (3, 'Utilizar la moneda de la suerte.', 'AUTOMATA_ROTO', 'ITEM_MONEDA_SUERTE', 0, 0, 0, 0, 0);
INSERT INTO Eventos VALUES (4, 'Pero si solo es una brisa de aire frío.', 'BRUMA_RASTREADORA', NULL, 15, 0, 0, 0, 0);
INSERT INTO Eventos VALUES (5, 'Intentar intimidar a tu reflejo.', 'CHARCO_REFLEJOS', NULL, 0, 0, 20, 0, 0);
INSERT INTO Eventos VALUES (6, 'Utilizar el Uranio-235.', 'CRANEO_RISUENO', 'ITEM_URANIO_235', 0, 0, 0, 0, 0);
INSERT INTO Eventos VALUES (7, 'Saltar sobre el elemental.', 'ELEMENTAL_LLAMA', NULL, 0, 0, 10, 0, 0);
INSERT INTO Eventos VALUES (8, 'Lanzarle la piedra de rio.', 'ESPECTRO_MEMORIA', 'ITEM_PIEDRA_RIO', 0, 0, 0, 0, 0);
INSERT INTO Eventos VALUES (9, 'Leerle el diario.', 'ESTATUA_LLORONA', 'ITEM_DIARIO', 0, 0, 0, 0, 0);
INSERT INTO Eventos VALUES (10, 'Hacerle gaslighting.', 'GOLEM_MUSGO', NULL, 0, 0, 0, 15, 0);
INSERT INTO Eventos VALUES (26, 'Invitar a la abuela a bailar tango.', 'EVENTO_ABUELA_GALLETAS', 'ITEM_TRAJE_IMPECABLE', 0, 0, 0, 0, 0);
INSERT INTO Eventos VALUES (27, 'Escribir tus últimas memorias en el diario.', 'EVENTO_ASCENSOR_POSIBILIDADES', 'ITEM_DIARIO', 0, 0, 0, 0, 0);
INSERT INTO Eventos VALUES (28, 'Revisas los apuntes de JavaScript de tu diario.', 'EVENTO_CUAJA_TEXTO', 'ITEM_DIARIO', 0, 0, 0, 0, 0);
INSERT INTO Eventos VALUES (29, 'Te suicidas con el cuchillo.', 'EVENTO_CUARTA_PARED', 'ITEM_CUCHILLO', 0, 0, 0, 0, 0);
INSERT INTO Eventos VALUES (30, 'Envías una carta de disculpas impregnada en Uranio-235.', 'EVENTO_DEMANDA_FONTANERO', 'ITEM_URANIO_235', 0, 0, 0, 0, 0);
INSERT INTO Eventos VALUES (31, 'Intentas asustar al gato.', 'EVENTO_GATO_CUANTICO', 'ITEM_PIEDRA_RIO', 0, 0, 0, 0, 0);
INSERT INTO Eventos VALUES (32, 'Intentar motivarlo con frases de Mr. Wonderful.', 'EVENTO_NPC_PARKING', 'ITEM_DIARIO', 0, 0, 0, 0, 0);
INSERT INTO Eventos VALUES (33, 'Formatear el sistema.', 'EVENTO_PANTALLA_AZUL', NULL, 0, 0, 0, 20, 0);
INSERT INTO Eventos VALUES (34, 'Participar en un concurso.', 'EVENTO_PROGRAMA_TV', NULL, 0, 0, 0, 0, 20);
INSERT INTO Eventos VALUES (35, 'Financiar el negocio.', 'EVENTO_PUBLICIDAD_EMERGENTE', 'ITEM_TRAJE_IMPECABLE', 0, 0, 0, 0, 0);
INSERT INTO Eventos VALUES (36, 'Lanzar moneda al aire para decidir.', 'EVENTO_PUENTE_ROTO', 'ITEM_MONEDA_SUERTE', 0, 0, 0, 0, 0);
INSERT INTO Eventos VALUES (37, 'Lanzar la piedra a través de la puerta para ver qué pasa.', 'EVENTO_PUERTA_MAGICA', 'ITEM_PIEDRA_RIO', 0, 0, 0, 0, 0);
